#!/bin/sh

datax_home="/data/juxin/com.juxin.etl/datax"

nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_activity.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_activity_detail.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_activity_user_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_adview_bid.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_adview_bid_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_adview_bid_price.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_an_custom_pkg.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_an_custom_pkg_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_api_spread.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_active.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_new_ver.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_new_ver_channel.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_new_ver_uid.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_ping.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_user_active.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_ver.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_version.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_ver_channel.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_app_ver_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_area.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_article_info.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_back_domain.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_back_domain_history.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_baidu_bid.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_baidu_bid_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_baidu_bid_price.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_baidu_login.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_behavior.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_belle_group.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_belle_group_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_belle_group_to_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_belle_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_block.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_block_item.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_channel_filter.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_angelpay_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_log_order.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_log_second.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_sp_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_user_first.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_user_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_charge_user_second.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_city.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_city_map.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_code.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_columns_priv.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_complain.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_complain_item.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_constellation.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_constellation_luck.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_db.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_deduction_money.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_dev_user_wechat_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_diamand_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_down_count.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_event.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_feedback.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_film.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_forbid_user_mac.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_func.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_games.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_fruit_redbag.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_fruit_withdraw.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_prize_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_prize_win_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_share_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_share_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_task_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_game_user_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_general_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_gift.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_gpay_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_h5_click_time.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_h5_login_tpl.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_help_category.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_help_keyword.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_help_relation.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_help_topic.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_horoscopes.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_host.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_iccid_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_image_md5.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_importData_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_integral_app.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_integral_app_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_integral_new_app.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_ios_custom_pkg.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_ios_custom_pkg_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_ip_address_lib.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_joke.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_keep_url.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_kf.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_live_anchor.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_live_banner.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_live_key_value.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_login_equipment_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_lucky.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_lucky_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_lucky_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_manager.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_manager_action_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_manager_group.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_manager_login_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_manager_operate_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_money_tree_cheater.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mpay_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mpay_charge_log_1.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mp_company.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mp_domain.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mp_options.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mp_options_child.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_new_cp.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_new_en.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_show_date.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_show_date_type.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user_.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user_copy.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user_cp.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user_cp_copy.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_user_en.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_msg_tpl_wy.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_mumu_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_myapp_keyword.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_ndb_binlog_index.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_novel.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_novel_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_novel_wechat_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_phone_info.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_plugin.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_position.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_precious.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_precious_day.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_prize.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_prize_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_prize_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_prize_new_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_proc.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_procs_priv.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_province.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_proxies_priv.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_push_ad.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_push_ad_config.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_push_ad_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_push_user_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_redbag_moneytree.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_redbag_ranking.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_reply_keyword.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_reply_keyword_tpl.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_activity.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_amount.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_app_user_action.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_app_ver.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_girl.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_msg_10_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_shangxian_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_user_abnormal.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_user_action.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_user_free.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_report_ver.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_resume.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_robots_tpl_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_root_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_rose.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sdk_active_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sdk_hejupay.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_servers.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sessions.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_setting.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_share.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_single_wechat_qrcode.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_slow_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sms.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sms_verify.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_channel.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_channel_config.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_click_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_click_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_click_log_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_click_sdk_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman_all_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman_dx.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman_dx_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman_imsi.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_dongman_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_get_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_heju.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_receive.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_receive_ido.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_send_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_test_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_upay360.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_user_info.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_view_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sp_view_region_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sys_notice.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_sys_session.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tables_priv.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_talent.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_talent_new.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_test_info.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_test_info_data.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_domain.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_peizhi.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_user_acount.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_user_income.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tg_user_withdraw.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_time_zone.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_time_zone_leap_second.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_time_zone_name.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_time_zone_transition.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_time_zone_transition_type.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_tree_url.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_ad.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_ad_config.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_ad_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_ad_report_all.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_check_uid.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_desk.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_notice.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_report_tmp.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_settlement.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_sid_content.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_uid_manage.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_user_table.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_union_user_xx.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_address.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_auth.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_avatar_verify.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_avatar_verify_status.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_bribery.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_bribery_receive.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_broadcast.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_complain.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_credit.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_detail.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_follow.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_gamekf_os.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_group.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_heart.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_help_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_help_new_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_ip_ban.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_kuplay.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_lang.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_login_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_men_avatar.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_message.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_message_count.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_message_fail.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_message_failed.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_message_female.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_msg_support.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_nickname.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_nickname_modify.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_online.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_online_client.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_online_wechat.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_orders.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_os.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_photo_album.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_photo_album_verify.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_pkgname.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_precious_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_require.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_rose.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_sayHi.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_sayHi_config.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_smspush_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_test.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_test_20170606.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_three.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_validation.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_video.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_visitors.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_wechat.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_wechat_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_wechat_os.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_wechat_scan.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_wish.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_yan_tmp.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_user_ycoin_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_video.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_video_formal.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_video_push.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_vote.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wechat_count.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_weixin.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_weixin_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wish_address.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wish_charge_log.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wish_credit.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_word_filter.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_word_filter_gift.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_word_filter_msg.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wy_active_imei.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wy_active_imei_enter.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wy_active_imei_sp.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wy_active_list.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_wy_active_report.json &
nohup python ${datax_home}/bin/datax.py ${datax_home}/job/job_mysql_hdfs_yht_settlement_list.json &
